name: Manual production release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string

concurrency:
  group: ${{ inputs.tag }}

jobs:
  release:
    uses: digabi/workflows-common/.github/workflows/digabi2-companion-app-prod-release.yml@e5bff07d5518390a6d7469e1de6bc9b26cf01fe3
    with:
      app-name: drawio
      aws-access-role: DrawioGithubActionsAccessRole
      tag: ${{ inputs.tag }}
    secrets: inherit
