name: Manual production release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true
        type: string

concurrency:
  group: ${{ inputs.tag }}

jobs:
  release:
    uses: digabi/workflows-common/.github/workflows/digabi2-companion-app-prod-release.yml@0017bfa09dde7d2ab15bf987d7579a842e3704fb
    with:
      app-name: drawio
      aws-access-role: DrawioGithubActionsAccessRole
      tag: ${{ inputs.tag }}
    secrets: inherit
